# Generated by Django 4.2.20 on 2025-03-13 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_police', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotdevice',
            options={'permissions': [('can_view_device_information', 'can view device information'), ('can_send_device_information', 'can send device information'), ('can_disable_device', 'can disable device')]},
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 12, 27, 23, 503235), null=True),
        ),
    ]
