# Generated by Django 4.2.20 on 2025-03-13 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_police', '0002_alter_iotdevice_options_alter_iotdevice_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdevice',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 16, 22, 54, 66375), null=True),
        ),
        migrations.CreateModel(
            name='IoTMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_time', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(db_index=True, max_length=50)),
                ('msg', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_msg', to='group_police.iotdevice')),
            ],
        ),
    ]
