# Generated by Django 4.2.20 on 2025-03-13 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_police', '0003_alter_iotdevice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='uid',
            field=models.CharField(default='aadf', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='device_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 16, 39, 3, 435537), null=True),
        ),
    ]
