# Generated by Django 4.2.20 on 2025-03-13 14:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group_police', '0004_iotdevice_uid_alter_iotdevice_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertodevicelog',
            name='at_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 17, 20, 37, 159597), null=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
